name: xrd_env
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h0ad9c76_9
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h477c42c_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.20=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.4.0=hac47afa_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=hd47e2ca_2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310hdb0e946_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=12.3.2=h5a1b470_0
  - icu=78.2=h637d24d_0
  - ipykernel=7.2.0=pyh6dadd2b_1
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py310h1e1005b_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.8=default_ha2db4b5_3
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.4=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_17
  - libglib=2.86.4=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_17
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libpng=1.6.55=h7351971_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.2=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libvulkan-loader=1.4.341.0=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - matplotlib=3.10.8=py310h5588dad_0
  - matplotlib-base=3.10.8=py310h0bdd906_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_455
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.2.6=py310h4987827_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.1=hf411b9b_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.3=py310hed136d8_2
  - parso=0.8.6=pyhcf101f3_0
  - pcre2=10.47=hd2b5f0e_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.1.1=py310h712baa7_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.9.2=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py310h1637853_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.10.2=py310h96c60bd_0
  - python=3.10.19=hc20f281_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py310h282bd7d_1
  - pyzmq=27.1.0=py310h535538e_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.10.2=h68b6638_4
  - scipy=1.15.2=py310h15c175c_0
  - setuptools=82.0.0=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=h3155e25_2
  - tk=8.6.13=h6ed50ae_3
  - tornado=6.5.4=py310h29418f3_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.1=py310h29418f3_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zeromq=4.3.5=h5bddc39_9
  - zlib-ng=2.3.3=h0261ad2_1
  - zstd=1.5.7=h534d264_6
prefix: C:\Users\Gabe\miniforge3\envs\xrd_env
